### ISSUE TITLE
[Exchange] Assertion failed

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/tdex-app#357]
Sending `0.018188` L-mBTC gives this error:
```
"AssertionError: Assertion failed
    at new push../node_modules/google-protobuf/google-protobuf.js.goog.asserts.AssertionError (http://localhost:8100/static/js/vendors~main.chunk.js:119336:20)
    at Object.push../node_modules/google-protobuf/google-protobuf.js.goog.asserts.doAssertFailure_ (http://localhost:8100/static/js/vendors~main.chunk.js:119365:7)
    at Object.push../node_modules/google-protobuf/google-protobuf.js.goog.asserts.assert (http://localhost:8100/static/js/vendors~main.chunk.js:119374:53)
    at push../node_modules/google-protobuf/google-protobuf.js.jspb.BinaryEncoder.writeUnsignedVarint64 (http://localhost:8100/static/js/vendors~main.chunk.js:124123:16)
    at push../node_modules/google-protobuf/google-protobuf.js.jspb.BinaryWriter.writeUnsignedVarint64_ (http://localhost:8100/static/js/vendors~main.chunk.js:124591:96)
    at push../node_modules/google-protobuf/google-protobuf.js.jspb.BinaryWriter.writeUint64 (http://localhost:8100/static/js/vendors~main.chunk.js:124639:89)
    at Function.push../node_modules/tdex-protobuf/generated/js/trade_pb.js.proto.MarketPriceRequest.serializeBinaryToWriter (http://localhost:8100/static/js/vendors~main.chunk.js:227565:12)
    at push../node_modules/tdex-protobuf/generated/js/trade_pb.js.proto.MarketPriceRequest.serializeBinary (http://localhost:8100/static/js/vendors~main.chunk.js:227536:28)
    at pa.a (http://localhost:8100/static/js/vendors~main.chunk.js:225256:22)
    at Ac (http://localhost:8100/static/js/vendors~main.chunk.js:127863:9)
    at Z.<anonymous> (http://localhost:8100/static/js/vendors~main.chunk.js:127774:12)
    at Z.push../node_modules/grpc-web/index.js.Z.R (http://localhost:8100/static/js/vendors~main.chunk.js:127775:14)
    at TradeClient.marketPrice (http://localhost:8100/static/js/vendors~main.chunk.js:225291:27)
    at http://localhost:8100/static/js/vendors~main.chunk.js:231593:21
    at new Promise (<anonymous>)
    at TraderClient.marketPrice (http://localhost:8100/static/js/vendors~main.chunk.js:231592:12)
    at calculatePrice (http://localhost:8100/static/js/main.chunk.js:27796:33)
    at http://localhost:8100/static/js/main.chunk.js:3066:94"
```

**Comment by tiero** [comment]
Looks like an error with decimals/unit conversion?

**Comment by Janaka-Steph** [comment]
I am pretty sure that this error is returned from the daemon.
